### ISSUE TITLE
Rename organization to "LibreSprite"

### ISSUE THREAD

**Issue by Symbian9** [aseprite-gpl/aseprite-gpl#20]
### TODO

- [ ] ~~https://github.com/aseprite-gpl~~ → http://github.com/LibreSprite

### REFERENCE

- https://github.com/aseprite-gpl/aseprite/issues/8
- https://github.com/aseprite-gpl/aseprite/issues/10

**Comment by akien-mga** [comment]
Duplicate of #8.
