### ISSUE TITLE
Rename repository to "LibreSprite"

### ISSUE THREAD

**Issue by Symbian9** [aseprite-gpl/aseprite-gpl#21]
### TODO

- [ ] ~~https://github.com/aseprite-gpl/aseprite~~ → http://github.com/LibreSprite/LibreSprite

### RELATED

- https://github.com/aseprite-gpl/aseprite/issues/20

### REFERENCE

- https://github.com/aseprite-gpl/aseprite/issues/8
- https://github.com/aseprite-gpl/aseprite/issues/10

**Comment by akien-mga** [comment]
Duplicate of #8.
